// Downloaded from: https://flagpedia.net/download/icons

const flagsMap = {
    // countries in hebrew
	"ישראל": "https://flagcdn.com/w80/il.png",
	"ארצות הברית": "https://flagcdn.com/w80/us.png",
	"קנדה": "https://flagcdn.com/w80/ca.png",
	"ברזיל": "https://flagcdn.com/w80/br.png",
	"ארגנטינה": "https://flagcdn.com/w80/ar.png",
	"גרמניה": "https://flagcdn.com/w80/de.png",
	"צרפת": "https://flagcdn.com/w80/fr.png",
	"ספרד": "https://flagcdn.com/w80/es.png",
	"פורטוגל": "https://flagcdn.com/w80/pt.png",
	"אנגליה": "https://flagcdn.com/w80/gb-eng.png",
	"איטליה": "https://flagcdn.com/w80/it.png",
	"הולנד": "https://flagcdn.com/w80/nl.png",
	"בלגיה": "https://flagcdn.com/w80/be.png",
	"שוויץ": "https://flagcdn.com/w80/ch.png",
	"אוסטריה": "https://flagcdn.com/w80/at.png",
	"שוודיה": "https://flagcdn.com/w80/se.png",
	"נורווגיה": "https://flagcdn.com/w80/no.png",
	"דנמרק": "https://flagcdn.com/w80/dk.png",
	"פינלנד": "https://flagcdn.com/w80/fi.png",
	"פולין": "https://flagcdn.com/w80/pl.png",
	"צ'כיה": "https://flagcdn.com/w80/cz.png",
	"סלובקיה": "https://flagcdn.com/w80/sk.png",
	"הונגריה": "https://flagcdn.com/w80/hu.png",
	"רומניה": "https://flagcdn.com/w80/ro.png",
	"בולגריה": "https://flagcdn.com/w80/bg.png",
	"יוון": "https://flagcdn.com/w80/gr.png",
	"טורקיה": "https://flagcdn.com/w80/tr.png",
    "מקדוניה": "https://flagcdn.com/w80/mk.png",
	"קרואטיה": "https://flagcdn.com/w80/hr.png",
	"סרביה": "https://flagcdn.com/w80/rs.png",
	"סלובניה": "https://flagcdn.com/w80/si.png",
	"אוקראינה": "https://flagcdn.com/w80/ua.png",
	"רוסיה": "https://flagcdn.com/w80/ru.png",
	"אירלנד": "https://flagcdn.com/w80/ie.png",
	"סקוטלנד": "https://flagcdn.com/w80/gb-sct.png",
	"ווילס": "https://flagcdn.com/w80/gb-wls.png",
	"יפן": "https://flagcdn.com/w80/jp.png",
	"דרום קוריאה": "https://flagcdn.com/w80/kr.png",
	"סין": "https://flagcdn.com/w80/cn.png",
	"הודו": "https://flagcdn.com/w80/in.png",
	"אוסטרליה": "https://flagcdn.com/w80/au.png",
	"ניו זילנד": "https://flagcdn.com/w80/nz.png",
	"איראן": "https://flagcdn.com/w80/ir.png",
	"עיראק": "https://flagcdn.com/w80/iq.png",
	"ערב הסעודית": "https://flagcdn.com/w80/sa.png",
	"איחוד האמירויות": "https://flagcdn.com/w80/ae.png",
	"קטאר": "https://flagcdn.com/w80/qa.png",
	"מצרים": "https://flagcdn.com/w80/eg.png",
	"מרוקו": "https://flagcdn.com/w80/ma.png",
	"תוניסיה": "https://flagcdn.com/w80/tn.png",
	"אלג'יריה": "https://flagcdn.com/w80/dz.png",
	"קמרון": "https://flagcdn.com/w80/cm.png",
	"ניגריה": "https://flagcdn.com/w80/ng.png",
	"סנגל": "https://flagcdn.com/w80/sn.png",
	"גאנה": "https://flagcdn.com/w80/gh.png",
	"דרום אפריקה": "https://flagcdn.com/w80/za.png",
	"מקסיקו": "https://flagcdn.com/w80/mx.png",
	"קולומביה": "https://flagcdn.com/w80/co.png",
	"צ'ילה": "https://flagcdn.com/w80/cl.png",
	"אורוגוואי": "https://flagcdn.com/w80/uy.png",
	"פרו": "https://flagcdn.com/w80/pe.png",
	"איסלנד": "https://flagcdn.com/w80/is.png",
    "חוף השנהב": "https://flagcdn.com/w80/ci.png",
    "פרגוואי": "https://flagcdn.com/w80/py.png",
    "אפגניסטן": "https://flagcdn.com/w80/af.png",
    "אלבניה": "https://flagcdn.com/w80/al.png",
    "סמואה האמריקנית": "https://flagcdn.com/w80/as.png",
    "אנדורה": "https://flagcdn.com/w80/ad.png",
    "אנגולה": "https://flagcdn.com/w80/ao.png",
    "אנגווילה": "https://flagcdn.com/w80/ai.png",
    "אנטארקטיקה": "https://flagcdn.com/w80/aq.png",
    "אנטיגואה וברבודה": "https://flagcdn.com/w80/ag.png",
    "ארמניה": "https://flagcdn.com/w80/am.png",
    "ג'מאיקה": "https://flagcdn.com/w80/jm.png",
    "ארובה": "https://flagcdn.com/w80/aw.png",
    "אזרבייג'ן": "https://flagcdn.com/w80/az.png",
    "איי בהאמה": "https://flagcdn.com/w80/bs.png",
    "בחריין": "https://flagcdn.com/w80/bh.png",
    "בנגלדש": "https://flagcdn.com/w80/bd.png",
    "ברבדוס": "https://flagcdn.com/w80/bb.png",
    "בלארוס": "https://flagcdn.com/w80/by.png",
    "צפון אירלנד": "https://flagcdn.com/w80/gb-nir.png",
    "בליז": "https://flagcdn.com/w80/bz.png",
    "בנין": "https://flagcdn.com/w80/bj.png",
    "ברמודה": "https://flagcdn.com/w80/bm.png",
    "בהוטן": "https://flagcdn.com/w80/bt.png",
    "אוזבקיסטן": "https://flagcdn.com/w80/uz.png",
    "בוליביה": "https://flagcdn.com/w80/bo.png",
    "בוסניה והרצגובינה": "https://flagcdn.com/w80/ba.png",
    "בוצואנה": "https://flagcdn.com/w80/bw.png",
    "טריטוריית האוקיינוס ההודי הבריטית": "https://flagcdn.com/w80/io.png",
    "ברוניי": "https://flagcdn.com/w80/bn.png",
    "בורקינה פאסו": "https://flagcdn.com/w80/bf.png",
    "בורונדי": "https://flagcdn.com/w80/bi.png",
    "קמבודיה": "https://flagcdn.com/w80/kh.png",
    "כף ורדה": "https://flagcdn.com/w80/cv.png",
    "איי קיימן": "https://flagcdn.com/w80/ky.png",
    "הרפובליקה המרכז-אפריקאית": "https://flagcdn.com/w80/cf.png",
    "צ'אד": "https://flagcdn.com/w80/td.png",
    "אי חג המולד": "https://flagcdn.com/w80/cx.png",
    "איי קוקוס": "https://flagcdn.com/w80/cc.png",
    "קומורו": "https://flagcdn.com/w80/km.png",
    "קונגו": "https://flagcdn.com/w80/cg.png",
    "קונגו הדמוקרטית": "https://flagcdn.com/w80/cd.png",
    "איי קוק": "https://flagcdn.com/w80/ck.png",
    "קלדוניה החדשה": "https://flagcdn.com/w80/nc.png",
    "קוסטה ריקה": "https://flagcdn.com/w80/cr.png",
    "קובה": "https://flagcdn.com/w80/cu.png",
    "קוסובו": "https://flagcdn.com/w80/xk.png",
    "קפריסין": "https://flagcdn.com/w80/cy.png",
    "ג'יבוטי": "https://flagcdn.com/w80/dj.png",
    "פנמה": "https://flagcdn.com/w80/pa.png",
    "דומיניקה": "https://flagcdn.com/w80/dm.png",
    "הרפובליקה הדומיניקנית": "https://flagcdn.com/w80/do.png",
    "אקוודור": "https://flagcdn.com/w80/ec.png",
    "אל סלבדור": "https://flagcdn.com/w80/sv.png",
    "גינאה המשוונית": "https://flagcdn.com/w80/gq.png",
    "אריתריאה": "https://flagcdn.com/w80/er.png",
    "אסטוניה": "https://flagcdn.com/w80/ee.png",
    "אתיופיה": "https://flagcdn.com/w80/et.png",
    "איי פוקלנד": "https://flagcdn.com/w80/fk.png",
    "איי פארו": "https://flagcdn.com/w80/fo.png",
    "פיג'י": "https://flagcdn.com/w80/fj.png",
    "גבון": "https://flagcdn.com/w80/ga.png",
    "גמביה": "https://flagcdn.com/w80/gm.png",
    "גאורגיה": "https://flagcdn.com/w80/ge.png",
    "גרינלנד": "https://flagcdn.com/w80/gl.png",
    "גרנדה": "https://flagcdn.com/w80/gd.png",
    "גוואדלופ": "https://flagcdn.com/w80/gp.png",
    "גואם": "https://flagcdn.com/w80/gu.png",
    "גואטמלה": "https://flagcdn.com/w80/gt.png",
    "גינאה": "https://flagcdn.com/w80/gn.png",
    "גינאה-ביסאו": "https://flagcdn.com/w80/gw.png",
    "גיאנה": "https://flagcdn.com/w80/gy.png",
    "האיטי": "https://flagcdn.com/w80/ht.png",
    "הונדורס": "https://flagcdn.com/w80/hn.png",
    "הונג קונג": "https://flagcdn.com/w80/hk.png",
    "אינדונזיה": "https://flagcdn.com/w80/id.png",
    "ירדן": "https://flagcdn.com/w80/jo.png",
    "קזחסטן": "https://flagcdn.com/w80/kz.png",
    "קניה": "https://flagcdn.com/w80/ke.png",
    "כווית": "https://flagcdn.com/w80/kw.png",
    "קירגיזסטן": "https://flagcdn.com/w80/kg.png",
    "לאוס": "https://flagcdn.com/w80/la.png",
    "לטביה": "https://flagcdn.com/w80/lv.png",
    "לבנון": "https://flagcdn.com/w80/lb.png",
    "לסוטו": "https://flagcdn.com/w80/ls.png",
    "ליבריה": "https://flagcdn.com/w80/lr.png",
    "לוב": "https://flagcdn.com/w80/ly.png",
    "ליכטנשטיין": "https://flagcdn.com/w80/li.png",
    "ליטא": "https://flagcdn.com/w80/lt.png",
    "קוראסאו": "https://flagcdn.com/w80/cw.png",
    "קאבו ורדה": "https://flagcdn.com/w80/cv.png",
    "לוקסמבורג": "https://flagcdn.com/w80/lu.png",

    // Clubs in hebrew:
    "פסז'": "/images/teams_logo/paris.png",
    "גלאטסראיי": "/images/teams_logo/galatasaray.png",
    "יובנטוס": "/images/teams_logo/juventus.png",
    "בנפיקה": "/images/teams_logo/benfica.png",
    "ריאל מדריד": "/images/teams_logo/real-madrid.png",
    "דורטמונד": "/images/teams_logo/dortmund.png",
    "אטאלנטה": "/images/teams_logo/atalanta.png",
    "מונקו": "/images/teams_logo/monaco.png",
    "קרבאח": "/images/teams_logo/qarabag.png",
    "ניוקאסל": "/images/teams_logo/newcastle.png",
    "בודו גלימט": "/images/teams_logo/bodo.png",
    "אינטר": "/images/teams_logo/inter.png",
    "ברוז'": "/images/teams_logo/brugge.png",
    "אתלטיקו מדריד": "/images/teams_logo/atletico.png",
    "אולימפיאקוס": "/images/teams_logo/olympiacos.png",
    "באייר לברקוזן": "/images/teams_logo/leverkusen.png",
    "ברצלונה": "/images/teams_logo/barcelona.png",
    "צ'לסי": "/images/teams_logo/chelsea.png",
    "ליברפול": "/images/teams_logo/liverpool.png",
    "טוטנהאם": "/images/teams_logo/tottenham.png",
    "ספורטינג": "/images/teams_logo/sporting.png",
    "מנצ'סטר סיטי": "/images/teams_logo/manchester-city.png",
    "ארסנל": "/images/teams_logo/arsenal.png",
    "באיירן מינכן": "/images/teams_logo/bayern.png"
};

export default flagsMap;
