// Downloaded from: https://flagpedia.net/download/icons

const flagsMap = {
	"ישראל": "https://flagcdn.com/w40/il.png",
	"ארצות הברית": "https://flagcdn.com/w40/us.png",
	"קנדה": "https://flagcdn.com/w40/ca.png",
	"ברזיל": "https://flagcdn.com/w40/br.png",
	"ארגנטינה": "https://flagcdn.com/w40/ar.png",
	"גרמניה": "https://flagcdn.com/w40/de.png",
	"צרפת": "https://flagcdn.com/w40/fr.png",
	"ספרד": "https://flagcdn.com/w40/es.png",
	"פורטוגל": "https://flagcdn.com/w40/pt.png",
	"אנגליה": "https://flagcdn.com/w40/gb-eng.png",
	"איטליה": "https://flagcdn.com/w40/it.png",
	"הולנד": "https://flagcdn.com/w40/nl.png",
	"בלגיה": "https://flagcdn.com/w40/be.png",
	"שוויץ": "https://flagcdn.com/w40/ch.png",
	"אוסטריה": "https://flagcdn.com/w40/at.png",
	"שוודיה": "https://flagcdn.com/w40/se.png",
	"נורווגיה": "https://flagcdn.com/w40/no.png",
	"דנמרק": "https://flagcdn.com/w40/dk.png",
	"פינלנד": "https://flagcdn.com/w40/fi.png",
	"פולין": "https://flagcdn.com/w40/pl.png",
	"צ'כיה": "https://flagcdn.com/w40/cz.png",
	"סלובקיה": "https://flagcdn.com/w40/sk.png",
	"הונגריה": "https://flagcdn.com/w40/hu.png",
	"רומניה": "https://flagcdn.com/w40/ro.png",
	"בולגריה": "https://flagcdn.com/w40/bg.png",
	"יוון": "https://flagcdn.com/w40/gr.png",
	"טורקיה": "https://flagcdn.com/w40/tr.png",
    "מקדוניה": "https://flagcdn.com/w40/mk.png",
	"קרואטיה": "https://flagcdn.com/w40/hr.png",
	"סרביה": "https://flagcdn.com/w40/rs.png",
	"סלובניה": "https://flagcdn.com/w40/si.png",
	"אוקראינה": "https://flagcdn.com/w40/ua.png",
	"רוסיה": "https://flagcdn.com/w40/ru.png",
	"אירלנד": "https://flagcdn.com/w40/ie.png",
	"סקוטלנד": "https://flagcdn.com/w40/gb-sct.png",
	"ווילס": "https://flagcdn.com/w40/gb-wls.png",
	"יפן": "https://flagcdn.com/w40/jp.png",
	"דרום קוריאה": "https://flagcdn.com/w40/kr.png",
	"סין": "https://flagcdn.com/w40/cn.png",
	"הודו": "https://flagcdn.com/w40/in.png",
	"אוסטרליה": "https://flagcdn.com/w40/au.png",
	"ניו זילנד": "https://flagcdn.com/w40/nz.png",
	"איראן": "https://flagcdn.com/w40/ir.png",
	"עיראק": "https://flagcdn.com/w40/iq.png",
	"ערב הסעודית": "https://flagcdn.com/w40/sa.png",
	"איחוד האמירויות": "https://flagcdn.com/w40/ae.png",
	"קטאר": "https://flagcdn.com/w40/qa.png",
	"מצרים": "https://flagcdn.com/w40/eg.png",
	"מרוקו": "https://flagcdn.com/w40/ma.png",
	"תוניסיה": "https://flagcdn.com/w40/tn.png",
	"אלג'יריה": "https://flagcdn.com/w40/dz.png",
	"קמרון": "https://flagcdn.com/w40/cm.png",
	"ניגריה": "https://flagcdn.com/w40/ng.png",
	"סנגל": "https://flagcdn.com/w40/sn.png",
	"גאנה": "https://flagcdn.com/w40/gh.png",
	"דרום אפריקה": "https://flagcdn.com/w40/za.png",
	"מקסיקו": "https://flagcdn.com/w40/mx.png",
	"קולומביה": "https://flagcdn.com/w40/co.png",
	"צ'ילה": "https://flagcdn.com/w40/cl.png",
	"אורוגוואי": "https://flagcdn.com/w40/uy.png",
	"פרו": "https://flagcdn.com/w40/pe.png",
	"איסלנד": "https://flagcdn.com/w40/is.png",
    "חוף השנהב": "https://flagcdn.com/w40/ci.png",
    "פרגוואי": "https://flagcdn.com/w40/py.png",
    "אפגניסטן": "https://flagcdn.com/w40/af.png",
    "אלבניה": "https://flagcdn.com/w40/al.png",
    "סמואה האמריקנית": "https://flagcdn.com/w40/as.png",
    "אנדורה": "https://flagcdn.com/w40/ad.png",
    "אנגולה": "https://flagcdn.com/w40/ao.png",
    "אנגווילה": "https://flagcdn.com/w40/ai.png",
    "אנטארקטיקה": "https://flagcdn.com/w40/aq.png",
    "אנטיגואה וברבודה": "https://flagcdn.com/w40/ag.png",
    "ארמניה": "https://flagcdn.com/w40/am.png",
    "ג'מאיקה": "https://flagcdn.com/w40/jm.png",
    "ארובה": "https://flagcdn.com/w40/aw.png",
    "אזרבייג'ן": "https://flagcdn.com/w40/az.png",
    "איי בהאמה": "https://flagcdn.com/w40/bs.png",
    "בחריין": "https://flagcdn.com/w40/bh.png",
    "בנגלדש": "https://flagcdn.com/w40/bd.png",
    "ברבדוס": "https://flagcdn.com/w40/bb.png",
    "בלארוס": "https://flagcdn.com/w40/by.png",
    "בליז": "https://flagcdn.com/w40/bz.png",
    "בנין": "https://flagcdn.com/w40/bj.png",
    "ברמודה": "https://flagcdn.com/w40/bm.png",
    "בהוטן": "https://flagcdn.com/w40/bt.png",
    "בוליביה": "https://flagcdn.com/w40/bo.png",
    "בוסניה והרצגובינה": "https://flagcdn.com/w40/ba.png",
    "בוצואנה": "https://flagcdn.com/w40/bw.png",
    "טריטוריית האוקיינוס ההודי הבריטית": "https://flagcdn.com/w40/io.png",
    "ברוניי": "https://flagcdn.com/w40/bn.png",
    "בורקינה פאסו": "https://flagcdn.com/w40/bf.png",
    "בורונדי": "https://flagcdn.com/w40/bi.png",
    "קמבודיה": "https://flagcdn.com/w40/kh.png",
    "כף ורדה": "https://flagcdn.com/w40/cv.png",
    "איי קיימן": "https://flagcdn.com/w40/ky.png",
    "הרפובליקה המרכז-אפריקאית": "https://flagcdn.com/w40/cf.png",
    "צ'אד": "https://flagcdn.com/w40/td.png",
    "אי חג המולד": "https://flagcdn.com/w40/cx.png",
    "איי קוקוס": "https://flagcdn.com/w40/cc.png",
    "קומורו": "https://flagcdn.com/w40/km.png",
    "קונגו": "https://flagcdn.com/w40/cg.png",
    "קונגו הדמוקרטית": "https://flagcdn.com/w40/cd.png",
    "איי קוק": "https://flagcdn.com/w40/ck.png",
    "קלדוניה החדשה": "https://flagcdn.com/w40/nc.png",
    "קוסטה ריקה": "https://flagcdn.com/w40/cr.png",
    "קובה": "https://flagcdn.com/w40/cu.png",
    "קוסובו": "https://flagcdn.com/w40/xk.png",
    "קפריסין": "https://flagcdn.com/w40/cy.png",
    "ג'יבוטי": "https://flagcdn.com/w40/dj.png",
    "פנמה": "https://flagcdn.com/w40/pa.png",
    "דומיניקה": "https://flagcdn.com/w40/dm.png",
    "הרפובליקה הדומיניקנית": "https://flagcdn.com/w40/do.png",
    "אקוודור": "https://flagcdn.com/w40/ec.png",
    "אל סלבדור": "https://flagcdn.com/w40/sv.png",
    "גינאה המשוונית": "https://flagcdn.com/w40/gq.png",
    "אריתריאה": "https://flagcdn.com/w40/er.png",
    "אסטוניה": "https://flagcdn.com/w40/ee.png",
    "אתיופיה": "https://flagcdn.com/w40/et.png",
    "איי פוקלנד": "https://flagcdn.com/w40/fk.png",
    "איי פארו": "https://flagcdn.com/w40/fo.png",
    "פיג'י": "https://flagcdn.com/w40/fj.png",
    "גבון": "https://flagcdn.com/w40/ga.png",
    "גמביה": "https://flagcdn.com/w40/gm.png",
    "גאורגיה": "https://flagcdn.com/w40/ge.png",
    "גרינלנד": "https://flagcdn.com/w40/gl.png",
    "גרנדה": "https://flagcdn.com/w40/gd.png",
    "גוואדלופ": "https://flagcdn.com/w40/gp.png",
    "גואם": "https://flagcdn.com/w40/gu.png",
    "גואטמלה": "https://flagcdn.com/w40/gt.png",
    "גינאה": "https://flagcdn.com/w40/gn.png",
    "גינאה-ביסאו": "https://flagcdn.com/w40/gw.png",
    "גיאנה": "https://flagcdn.com/w40/gy.png",
    "האיטי": "https://flagcdn.com/w40/ht.png",
    "הונדורס": "https://flagcdn.com/w40/hn.png",
    "הונג קונג": "https://flagcdn.com/w40/hk.png",
    "אינדונזיה": "https://flagcdn.com/w40/id.png",
    "ירדן": "https://flagcdn.com/w40/jo.png",
    "קזחסטן": "https://flagcdn.com/w40/kz.png",
    "קניה": "https://flagcdn.com/w40/ke.png",
    "כווית": "https://flagcdn.com/w40/kw.png",
    "קירגיזסטן": "https://flagcdn.com/w40/kg.png",
    "לאוס": "https://flagcdn.com/w40/la.png",
    "לטביה": "https://flagcdn.com/w40/lv.png",
    "לבנון": "https://flagcdn.com/w40/lb.png",
    "לסוטו": "https://flagcdn.com/w40/ls.png",
    "ליבריה": "https://flagcdn.com/w40/lr.png",
    "לוב": "https://flagcdn.com/w40/ly.png",
    "ליכטנשטיין": "https://flagcdn.com/w40/li.png",
    "ליטא": "https://flagcdn.com/w40/lt.png",
    "קוראסאו": "https://flagcdn.com/w40/cw.png",
    "קאבו ורדה": "https://flagcdn.com/w40/cv.png",
    "לוקסמבורג": "https://flagcdn.com/w40/lu.png"
};

export default flagsMap;
