const ClosedMatches = () => {
    // TODO: CREATE A LIST WITH THE MATCHES THAT STARTED, FOR EACH MATCH, GIVE THE OPTION TO SEE ALL FRIEENDS BETS
    // TODO: WHEN CLICK ON SPECIFIC MATCH TO SHOW THE FRIENDS BETS, STORE THE MATCH ID TO RETRIEVE THE MATCH DATA
  return (
    <div>ClosedMatches</div>
  )
}

export default ClosedMatches