const ClosedMatches = () => {
    // TODO: WHEN CREATE THE MATCH OBJECT(SEND TO MATCHLIST COMPONENT), NEED TO ADD THE FOLLOWOING PROPERTIES: ISSTARTED=TRUE AND THE LIST OF DB_SCORE_BETS FROM THE BET_SLICE(TO SHOW ONLY THE SCORES) - SEE THE PROPERTIES NAMES IN MY_BETS COMPONENT
    // TODO: CREATE A LIST WITH THE MATCHES THAT STARTED, FOR EACH MATCH, GIVE THE OPTION TO SEE ALL FRIEENDS BETS
    // TODO: WHEN CLICK ON SPECIFIC MATCH TO SHOW THE FRIENDS BETS, STORE THE MATCH ID TO RETRIEVE THE MATCH DATA
  return (
    <div>ClosedMatches</div>
  )
}

export default ClosedMatches